board component update
axxcident/gomoku-gurus pull request #12
Opened 2023-10-26 11:53 UTC by MaximilianBakaldin

2023-10-26 12:31 UTC, axxcident requested changes
Bra jobbat men CSS måste fixas. Kan ej vara **position:absolute** för det funkar aldrig på någon annan skärmstorlek.

2023-10-26 12:31 UTC, axxcident commented on client/src/App.css
> +        position: absolute;
Borde ej vara **position:absolute**. Det betyder att det bara funkar på din skärm(storlek) men ej på någon annan storlek.
![Skärmbild 2023-10-26 142553](https://github.com/axxcident/gomoku-gurus/assets/112471629/1b21e10c-2568-40a2-9cab-c52f16974bb5)

2023-10-26 13:48 UTC, MaximilianBakaldin commented on client/src/App.css
> +        position: absolute;
fixar

2023-10-27 13:46 UTC, axxcident approved these changes

2023-10-27 13:48 UTC, merged